Update workflow

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -1,32 +1,35 @@
-name: Deploy Sphinx to GitHub Pages
+# Deploy Sphinx.  This could be shorter, but we also do some extra
+# stuff.
+#
+# License: CC-0.  This is the canonical location of this file, which
+# you may want to link to anyway:
+#   https://github.com/coderefinery/sphinx-lesson-template/blob/main/.github/workflows/sphinx.yml
+#  https://raw.githubusercontent.com/coderefinery/sphinx-lesson-template/main/.github/workflows/sphinx.yml
 
-on:
-  push:
-    branches: ["docs/sphinx"]
+name: sphinx
+on: [push, pull_request, workflow_dispatch]
 
-  pull_request:
-    types: ["opened", "reopened", "synchronize"]
-
-  workflow_dispatch:
-
-# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
-permissions:
-  contents: read
-  pages: write
-  id-token: write
-
-# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
-# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
-concurrency:
-  group: "pages"
-  cancel-in-progress: false
+env:
+  DEFAULT_BRANCH: "main"
+  # If these SPHINXOPTS are enabled, then be strict about the
+  # builds and fail on any warnings.
+  #SPHINXOPTS: "-W --keep-going -T"
+  GENERATE_SINGLEHTML: true # to enable, must be 'true' lowercase
+  MULTIBRANCH: true # to enable, must be 'true' lowercase
 
 jobs:
   build:
+    name: Build
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
+
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+      # https://github.com/marketplace/actions/checkout
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          lfs: true
 
       - name: Install uv
         uses: astral-sh/setup-uv@v5
@@ -39,27 +42,113 @@ jobs:
         with:
           python-version-file: ".python-version"
 
-      - name: Add dependencies, build site
+      - name: Install the project
+        run: uv sync --locked --all-extras --dev
+
+        # Debug
+      - name: Debugging information
+        env:
+          ref: ${{github.ref}}
+          event_name: ${{github.event_name}}
+          head_ref: ${{github.head_ref}}
+          base_ref: ${{github.base_ref}}
         run: |
-          uv venv
-          uv sync --all-extras
-          make html
+          echo "github.ref: ${ref}"
+          echo "github.event_name: ${event_name}"
+          echo "github.head_ref: ${head_ref}"
+          echo "github.base_ref: ${base_ref}"
+          echo "GENERATE_SINGLEHTML: ${GENERATE_SINGLEHTML}"
+          set -x
+          git rev-parse --abbrev-ref HEAD
+          git branch
+          git branch -a
+          git remote -v
+          python -V
+          pip list --not-required
+          pip list
 
-      - name: Set up Pages
-        uses: actions/configure-pages@v5
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v3
+      # Build
+      - uses: ammaraskar/sphinx-problem-matcher@master
+      - name: Build Sphinx docs (dirhtml)
+        # SPHINXOPTS used via environment variables
+        run: |
+          make dirhtml
+          # This fixes broken copy button icons, as explained in
+          #   https://github.com/coderefinery/sphinx-lesson/issues/50
+          #   https://github.com/executablebooks/sphinx-copybutton/issues/110
+          # This can be removed once these PRs are accepted (but the
+          # fixes also need to propagate to other themes):
+          #   https://github.com/sphinx-doc/sphinx/pull/8524
+          #   https://github.com/readthedocs/sphinx_rtd_theme/pull/1025
+          sed -i 's/url_root="#"/url_root=""/' _build/dirhtml/index.html || true
+
+      # singlehtml
+      - name: Generate singlehtml
+        if: ${{ env.GENERATE_SINGLEHTML == 'true' }}
+        run: |
+          make singlehtml
+          mv _build/singlehtml/ _build/dirhtml/singlehtml/
+
+      # Stage all deployed assets in _gh-pages/ for simplicity, and to
+      # prepare to do a multi-branch deployment.
+      - name: Copy deployment data to _gh-pages/
+        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
+        run: rsync -a _build/dirhtml/ _gh-pages/
+
+      # Use gh-pages-multibranch to multiplex different branches into
+      # one deployment. See
+      # https://github.com/coderefinery/gh-pages-multibranch
+      - name: gh-pages multibranch
+        uses: coderefinery/gh-pages-multibranch@main
+        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && env.MULTIBRANCH == 'true' }}
         with:
-          path: "build/html"
+          directory: _gh-pages/
+          default_branch: ${{ env.DEFAULT_BRANCH }}
+          publish_branch: gh-pages
 
+      # Add the .nojekyll file
+      - name: nojekyll
+        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
+        run: |
+          touch _gh-pages/.nojekyll
+
+      # Save artifact for the next step.
+      - uses: actions/upload-artifact@v4
+        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
+        with:
+          name: gh-pages-build
+          path: _gh-pages/
+
+  # Deploy in a separate job so that write permissions are restricted
+  # to the minimum steps.
   deploy:
+    name: Deploy
     runs-on: ubuntu-latest
     needs: build
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
+    # This if can't use the env context - find better way later.
+    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
+    permissions:
+      contents: write
+
     steps:
-      - name: Deploy to GitHub Pages
-        id: deployment
-        if: github.ref == 'refs/heads/main'
-        uses: actions/deploy-pages@v4
+      - uses: actions/download-artifact@v4
+        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && ( env.MULTIBRANCH == 'true' || github.ref == format('refs/heads/{0}', env.DEFAULT_BRANCH )) }}
+        with:
+          name: gh-pages-build
+          path: _gh-pages/
+
+      # As of 2023, we could publish to pages via a Deployment.  This
+      # isn't done yet to give it time to stabilize (out of beta), and
+      # also having a gh-pages branch to check out is rather
+      # convenient.
+
+      # Deploy
+      # https://github.com/peaceiris/actions-gh-pages
+      - name: Deploy
+        uses: peaceiris/actions-gh-pages@v3
+        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && ( env.MULTIBRANCH == 'true' || github.ref == format('refs/heads/{0}', env.DEFAULT_BRANCH )) }}
+        with:
+          publish_branch: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: _gh-pages/
+          force_orphan: true
